name: Deploy to Kubernetes

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu:latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: iyudesu/app:latest

    - name: Deploy to Kubernetes
      uses: iyudesu/kubectl-action@master
      with:
        kube_config_data: ${{ secrets.KUBE_CONFIG_DATA }}
        args: apply -f deployment.yaml -f service.yaml
